spring:
  application:
    name: barbearia-web-site
  servlet:
    context-path: /api/barbearia

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

